#!/bin/sh
# Convert PostScript to PDF using LaTeX recommended parameters.
# Adjust default PAPERSIZE as needed.
exec ps2pdfwr -sPAPERSIZE=a4 -dPDFSETTINGS=/printer -dCompatibilityLevel=1.3 -dMaxSubsetPct=100 -dSubsetFonts=true -dEmbedAllFonts=true "$@"
